/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'surface-container-highest': '#353534',
        'surface-container-high': '#2a2a2a',
        surface: '#131313',
        'on-surface-variant': '#c7c4d7',
        primary: '#c0c1ff',
        'primary-fixed': '#e1e0ff',
        'tertiary-fixed': '#e2e2e2',
        secondary: '#4cd7f6',
        'surface-container': '#201f1f',
        tertiary: '#c6c6c7',
        'surface-tint': '#c0c1ff',
        'tertiary-fixed-dim': '#c6c6c7',
        'on-primary-container': '#0d0096',
        'on-primary-fixed-variant': '#2f2ebe',
        'on-secondary-container': '#00424e',
        'on-tertiary': '#2f3131',
        'on-primary': '#1000a9',
        'secondary-fixed-dim': '#4cd7f6',
        'error-container': '#93000a',
        'on-secondary-fixed': '#001f26',
        outline: '#908fa0',
        'on-background': '#e5e2e1',
        'inverse-primary': '#494bd6',
        background: '#131313',
        'on-tertiary-fixed': '#1a1c1c',
        'inverse-on-surface': '#313030',
        'surface-container-low': '#1c1b1b',
        'tertiary-container': '#767777',
        'on-tertiary-fixed-variant': '#454747',
        'on-surface': '#e5e2e1',
        'on-primary-fixed': '#07006c',
        'secondary-container': '#03b5d3',
        'inverse-surface': '#e5e2e1',
        'outline-variant': '#464554',
        'secondary-fixed': '#acedff',
        'surface-bright': '#3a3939',
        'surface-container-lowest': '#0e0e0e',
        'surface-variant': '#353534',
        error: '#ffb4ab',
        'on-tertiary-container': '#040506',
        'surface-dim': '#131313',
        'on-error-container': '#ffdad6',
        'on-secondary': '#003640',
        'primary-container': '#8083ff',
        'on-secondary-fixed-variant': '#004e5c',
        'primary-fixed-dim': '#c0c1ff',
        'on-error': '#690005',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      fontFamily: {
        'display-xl': ['Geist', 'sans-serif'],
        'headline-lg': ['Geist', 'sans-serif'],
        'headline-md': ['Geist', 'sans-serif'],
        caption: ['Geist', 'sans-serif'],
        'body-md': ['Geist', 'sans-serif'],
        'body-lg': ['Geist', 'sans-serif'],
        'label-mono': ['JetBrains Mono', 'monospace'],
      },
    },
  },
  plugins: [],
}
